"""initial schema

Revision ID: e647cb26a19e
Revises: 
Create Date: 2026-03-11 12:50:09.060131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e647cb26a19e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_prefix', sa.String(length=500), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('label_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preprocessing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotation_project_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_datasets_org_project', 'image_datasets', ['organization_id', 'project_id'], unique=False)
    op.create_index('idx_datasets_status', 'image_datasets', ['status'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('annotation_count', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('label_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotation_format', sa.String(length=30), nullable=False),
    sa.Column('s3_manifest_key', sa.String(length=500), nullable=True),
    sa.Column('s3_annotations_key', sa.String(length=500), nullable=True),
    sa.Column('s3_meta_key', sa.String(length=500), nullable=True),
    sa.Column('preprocessing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['image_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_dataset', 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index('idx_version_dataset_number', 'dataset_versions', ['dataset_id', 'version_number'], unique=True)
    op.create_table('image_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['image_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_images_content_hash', 'image_records', ['content_hash'], unique=False)
    op.create_index('idx_images_dataset_status', 'image_records', ['dataset_id', 'status'], unique=False)
    op.create_index('idx_images_perceptual_hash', 'image_records', ['perceptual_hash'], unique=False)
    op.create_table('preprocessing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('vm_instance_id', sa.String(length=255), nullable=True),
    sa.Column('vm_ip', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('webhook_token', sa.String(length=255), nullable=False),
    sa.Column('images_total', sa.Integer(), nullable=False),
    sa.Column('images_processed', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('images_excluded', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('exclusion_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resource_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['image_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_token')
    )
    op.create_index('idx_preprocess_dataset', 'preprocessing_jobs', ['dataset_id'], unique=False)
    op.create_index('idx_preprocess_status', 'preprocessing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_preprocess_status', table_name='preprocessing_jobs')
    op.drop_index('idx_preprocess_dataset', table_name='preprocessing_jobs')
    op.drop_table('preprocessing_jobs')
    op.drop_index('idx_images_perceptual_hash', table_name='image_records')
    op.drop_index('idx_images_dataset_status', table_name='image_records')
    op.drop_index('idx_images_content_hash', table_name='image_records')
    op.drop_table('image_records')
    op.drop_index('idx_version_dataset_number', table_name='dataset_versions')
    op.drop_index('idx_version_dataset', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index('idx_datasets_status', table_name='image_datasets')
    op.drop_index('idx_datasets_org_project', table_name='image_datasets')
    op.drop_table('image_datasets')
    # ### end Alembic commands ###
